services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql
    environment:
      ACCEPT_EULA: "Y"
      MSSQL_SA_PASSWORD: "Str0ngP@ssw0rd!" # Ensure this meets SQL Server password complexity requirements
      MSSQL_PID: "Developer"
      MSSQL_AGENT_ENABLED: "true"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql # Persist SQL Server data
      - ~/Desktop/Projectiles/data_engineering/portfolio/warehouse/project/robust_dwh/datasets:/datasets # Mount datasets directory
volumes:
  mssql_data: